#!/bin/bash

# Route Structure Refactor - Sequential Session Launcher
# Run this script to launch stories in correct order (R1 must complete before R2)
# Estimated time: 4-5 hours total (SEQUENTIAL execution required)

PROJECT_DIR="/Users/kalyanchandana/Documents/GitHub/2Sat-lite"

echo "🚀 Launching Route Structure Refactor Sessions..."
echo ""
echo "PROJECT: Route Structure Refactor + Core Pages"
echo "Linear: https://linear.app/2s6y/project/route-structure-refactor-core-pages-e5b7cd50cc77"
echo "Stories: 2 (SEQUENTIAL - R2 blocked by R1)"
echo ""

echo "⚠️  IMPORTANT: These stories MUST run sequentially!"
echo "R2 needs the correct contribute route from R1 to update navigation links."
echo ""

# Phase 1: Route Migration
echo "📍 PHASE 1: Route Migration (MUST complete first)"
echo ""

echo "🔷 Story R1: Migrate Contribution Route (2-3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-41"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-R1: Migrate Contribution Form to Correct Route from Linear issue 2S6-41."
echo ""
echo "Move contribution form from /contribute to /groups/[groupId]/contribute."
echo "Use frontend-dev agent."
echo ""
echo "Tasks:"
echo "1. Create: app/groups/[groupId]/contribute/page.tsx"
echo "2. Update component to extract groupId from URL params (not state)"
echo "3. Remove group tabs component (single group context only)"
echo "4. Update navigation links in dashboard"
echo "5. Update preview button navigation"
echo "6. Delete: app/contribute/ directory"
echo ""
echo "Acceptance criteria:"
echo "- New route exists at /groups/[groupId]/contribute/page.tsx"
echo "- Old route /app/contribute/ deleted"
echo "- URL param extraction works (groupId from route)"
echo "- User access validated (non-members redirected)"
echo "- No group tabs"
echo "- Dashboard links updated"
echo "- No broken links: grep -r 'href=\"/contribute\"' app/ returns 0 results"
echo "- TypeScript compiles"
echo "- Mobile-responsive (3 breakpoints)"
echo ""
echo "See full details: .claude/projects/active/2025-10-route-structure/STORY-R1-migrate-route.md"
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "⏸️  DO NOT START STORY-R2 UNTIL R1 IS 100% COMPLETE"
echo ""
read -p "Press Enter when STORY-R1 is COMPLETE to launch Story R2..."
echo ""

# Phase 2: Missing Pages (after R1 complete)
echo "📍 PHASE 2: Missing Pages (after R1 complete)"
echo ""

echo "🔷 Story R2: Create Missing Core Pages (2-3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-43"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-R2: Create Missing Core Pages from Linear issue 2S6-43."
echo ""
echo "Create group home page and archive page with navigation integration."
echo "Use frontend-dev agent."
echo ""
echo "Files to create:"
echo "- app/groups/[groupId]/page.tsx (Group home)"
echo "- app/groups/[groupId]/archive/page.tsx (Archive)"
echo "- components/groups/ContributionStatusCard.tsx"
echo "- components/groups/QuickActionsGrid.tsx"
echo "- components/groups/GroupStatsCard.tsx"
echo "- components/groups/ArchiveIssueCard.tsx"
echo ""
echo "Files to modify:"
echo "- app/dashboard/page.tsx (group cards link to group home, not settings)"
echo ""
echo "Acceptance criteria:"
echo "Group Home Page:"
echo "- Route /groups/[groupId]/page.tsx exists"
echo "- Shows contribution status (draft/submitted/locked)"
echo "- Shows quick actions (contribute/latest/archive/settings)"
echo "- Back button → dashboard, settings icon → settings"
echo ""
echo "Archive Page:"
echo "- Route /groups/[groupId]/archive/page.tsx exists"
echo "- Lists all past issues (newest first)"
echo "- Shows month, date sent, contributor count"
echo "- View Issue button works"
echo "- Empty state when no issues"
echo "- Back button → group home"
echo ""
echo "Navigation Integration:"
echo "- Dashboard → Group Home (click group card)"
echo "- Group Home → Contribute/Archive/Latest/Settings"
echo "- Archive → Individual Issue"
echo "- No broken links"
echo ""
echo "See full details: .claude/projects/active/2025-10-route-structure/STORY-R2-missing-pages.md"
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "✅ All sessions launched!"
echo ""
echo "⏱️  Estimated completion time:"
echo "   - Phase 1 (R1): 2-3 hours"
echo "   - Phase 2 (R2): 2-3 hours"
echo "   - Total: 4-5 hours (SEQUENTIAL)"
echo ""
echo "📊 Progress tracking:"
echo "   Update: .claude/projects/active/2025-10-route-structure/STORY_TRACKER.md"
echo ""
