#!/bin/bash

# Deadline Enforcement - Parallel Session Launcher
# Run this script to launch both stories in separate terminal tabs
# Estimated time: 2.5 hours total (1.5 hours wall time with parallel execution)

PROJECT_DIR="/Users/kalyanchandana/Documents/GitHub/2Sat-lite"

echo "🚀 Launching Deadline Enforcement Sessions..."
echo ""
echo "PROJECT: Deadline Enforcement"
echo "Linear: https://linear.app/2s6y/project/deadline-enforcement-4486c62c1388"
echo "Stories: 2 (both parallelizable)"
echo ""

echo "📍 PARALLEL DEVELOPMENT: Run both simultaneously"
echo ""

echo "🔷 Story B1: Backend Deadline Validation (1.5 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-35"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-B1: Deadline Calculation + canEdit Query from Linear issue 2S6-35."
echo ""
echo "Add backend deadline validation. Calculate editDeadline on contribution creation, provide canEdit query, and block edits after deadline."
echo "Use backend-dev agent."
echo ""
echo "Files to create:"
echo "- convex/helpers/deadlines.ts"
echo "- convex/contributions.test.ts"
echo ""
echo "Files to modify:"
echo "- convex/contributions.ts (add canEdit query, update createOrUpdate and submit mutations)"
echo ""
echo "Acceptance criteria:"
echo "- canEdit query returns { canEdit: boolean, reason: string|null, deadline: number|null }"
echo "- createOrUpdate blocks edits after deadline with ConvexError"
echo "- submit blocks submission after deadline"
echo "- editDeadline calculated correctly (day before 2nd Saturday at 11:59 PM)"
echo "- Unit tests passing (6/6)"
echo ""
echo "See full details: .claude/projects/active/2025-10-deadline-enforcement/STORY-B1-deadline-validation.md"
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story B1 session..."
echo ""

echo "🔷 Story F1: Frontend UI Lock (1 hour)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-38"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-F1: Lock UI After Deadline from Linear issue 2S6-38."
echo ""
echo "Replace hardcoded 'isLocked = false' stub with real canEdit query. Lock UI when deadline passes."
echo "Use frontend-dev agent."
echo ""
echo "Files to modify:"
echo "- app/contribute/page.tsx (remove stub at line 101, add canEdit query)"
echo "- components/forms/PhotoWall.tsx (add disabled prop support)"
echo ""
echo "Files to create:"
echo "- tests/e2e/contribution-deadline.spec.ts"
echo ""
echo "Acceptance criteria:"
echo "- Hardcoded 'isLocked = false' removed"
echo "- canEdit query called when contributionId exists"
echo "- Form locked (inputs disabled) when canEdit returns false"
echo "- Locked banner shows formatted deadline date"
echo "- Save attempts show error toast with deadline"
echo "- Backend errors (DEADLINE_PASSED) displayed correctly"
echo "- E2E tests passing (4/4)"
echo ""
echo "See full details: .claude/projects/active/2025-10-deadline-enforcement/STORY-F1-lock-ui.md"
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "✅ All sessions launched!"
echo ""
echo "⏱️  Estimated completion time:"
echo "   - Both stories in parallel: 1.5 hours"
echo ""
echo "📊 Progress tracking:"
echo "   Update: .claude/projects/active/2025-10-deadline-enforcement/STORY_TRACKER.md"
echo ""
