#!/bin/bash

# Contribution Reminders + Exclusion - Multi-Phase Session Launcher
# Estimated time: 11 hours total (5h parallel + 2h + 3h + 1h buffer)

PROJECT_DIR="/Users/kalyanchandana/Documents/GitHub/2Sat-lite"

echo "🚀 Launching Contribution Reminders + Exclusion Sessions..."
echo ""
echo "PROJECT: Contribution Reminders + Exclusion Logic"
echo "Linear: https://linear.app/2s6y/project/contribution-reminders-exclusion-logic-340c2e86ade5"
echo "Stories: 4 (2 parallelizable + 1 sequential + 1 integration)"
echo ""

# Phase 1: Parallel Development
echo "📍 PHASE 1: Parallel Development (run simultaneously)"
echo ""

echo "🔷 Story B1: Reminder Cron Jobs (3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-44"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-B1: Reminder Cron Jobs from Linear issue 2S6-44."
echo ""
echo "Create 3 cron jobs that send contribution reminders at 7 days, 3 days, and 1 day before deadline."
echo "Use backend-dev agent."
echo ""
echo "Files to create:"
echo "- convex/crons/reminderHelpers.ts"
echo "- convex/crons/sevenDayReminder.ts"
echo "- convex/crons/threeDayReminder.ts"
echo "- convex/crons/oneDayReminder.ts"
echo "- convex/crons/reminderHelpers.test.ts"
echo ""
echo "Files to modify:"
echo "- convex/crons.ts (register 3 new schedules)"
echo ""
echo "Acceptance criteria:"
echo "- 3 cron jobs registered (7d, 3d, 1d)"
echo "- Crons run daily at 9am UTC"
echo "- Only send reminders on exact days (7, 3, 1 before deadline)"
echo "- Only non-contributors receive reminders"
echo "- Notifications created with type: contribution_reminder"
echo "- Unit tests passing (12/12)"
echo ""
echo "See Linear issue for full implementation details."
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story B1 session..."
echo ""

echo "🔷 Story F1: Exclusion Empty State UI (3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-46"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-F1: Exclusion Empty State UI from Linear issue 2S6-46."
echo ""
echo "Display informative empty state when user was excluded from newsletter due to not contributing."
echo "Use frontend-dev agent."
echo ""
echo "Files to create:"
echo "- components/ExclusionEmptyState.tsx"
echo "- tests/visual/exclusion-empty-state.spec.ts"
echo ""
echo "Files to modify:"
echo "- app/groups/[groupId]/issues/[issueId]/page.tsx (add exclusion check)"
echo ""
echo "Acceptance criteria:"
echo "- Empty state shows when user in excludedMemberIds"
echo "- Clear explanation why user was excluded"
echo "- Action buttons (Contribute Next Month, View Past Issues)"
echo "- Design system compliant (DaisyUI)"
echo "- Responsive (mobile, tablet, desktop)"
echo "- Visual tests passing (3 breakpoints)"
echo ""
echo "See Linear issue for full implementation details."
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story F1 session..."
echo ""

# Phase 2: Reminder Email Templates (blocked by B1)
echo "📍 PHASE 2: Reminder Email Templates (WAIT for B1 to complete)"
echo ""

echo "⚠️  WAIT: Ensure STORY-B1 is 100% complete before starting this"
echo ""
read -p "Press Enter when B1 is COMPLETE to launch Story B2..."
echo ""

echo "🔷 Story B2: Reminder Email Templates (2 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-45"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-B2: Reminder Email Templates + Delivery from Linear issue 2S6-45."
echo ""
echo "Create email templates for contribution reminders and integrate with notification watcher."
echo "Use backend-dev agent."
echo ""
echo "Files to create:"
echo "- emails/ReminderEmail.tsx"
echo "- (notification watcher updates)"
echo ""
echo "Acceptance criteria:"
echo "- ReminderEmail.tsx template created"
echo "- Email sent via Resend when notification created"
echo "- Subject: 'Time to share your monthly update for [Group Name]'"
echo "- CTA button: 'Contribute Now'"
echo "- Email delivery tracked"
echo ""
echo "See Linear issue for full implementation details."
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story B2 session..."
echo ""

# Phase 3: Integration Testing (blocked by all)
echo "📍 PHASE 3: Integration Testing (WAIT for ALL stories to complete)"
echo ""

echo "⚠️  WAIT: Ensure B1, F1, and B2 are 100% complete before starting this"
echo ""
read -p "Press Enter when B1 + F1 + B2 are COMPLETE to launch Story I1..."
echo ""

echo "🔷 Story I1: E2E Tests + Exclusion Notifications (3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-47"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-I1: Exclusion Notifications + E2E Reminder Tests from Linear issue 2S6-47."
echo ""
echo "Send notifications to excluded members after newsletter published. Verify entire reminder system E2E."
echo "Use orchestrator agent."
echo ""
echo "Files to create:"
echo "- tests/e2e/reminders.spec.ts"
echo "- (exclusion notification logic)"
echo ""
echo "Acceptance criteria:"
echo "- Excluded members receive notifications after newsletter sent"
echo "- E2E tests verify reminder cron timing"
echo "- E2E tests verify email delivery"
echo "- E2E tests verify exclusion logic"
echo "- All tests passing"
echo ""
echo "See Linear issue for full implementation details."
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "✅ All sessions launched!"
echo ""
echo "⏱️  Estimated completion time:"
echo "   - Phase 1 (B1 + F1 parallel): 3 hours"
echo "   - Phase 2 (B2): 2 hours"
echo "   - Phase 3 (I1): 3 hours"
echo "   - Total: ~8-9 hours wall time"
echo ""
echo "📊 Progress tracking:"
echo "   Update: .claude/projects/active/2025-10-reminders-exclusion/STORY_TRACKER.md"
echo ""
