#!/bin/bash

# Email Preferences System - Parallel Session Launcher
# Run this script to launch both stories in separate terminal tabs
# Estimated time: 4 hours total (2 hours wall time with parallel execution)

PROJECT_DIR="/Users/kalyanchandana/Documents/GitHub/2Sat-lite"

echo "🚀 Launching Email Preferences System Sessions..."
echo ""
echo "PROJECT: Email Preferences System"
echo "Linear: https://linear.app/2s6y/project/email-preferences-system-3502f31da2dd"
echo "Stories: 2 (both parallelizable)"
echo ""

echo "📍 PARALLEL DEVELOPMENT: Run both simultaneously"
echo ""

echo "🔷 Story EP1: Backend Schema + Logic (2 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-40"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-EP1: Email Preferences Schema + Backend Logic from Linear issue 2S6-40."
echo ""
echo "Add emailPreferences field to users schema with 7 preference types. Create backend logic to check preferences before sending emails."
echo "Use backend-dev agent."
echo ""
echo "Files to create:"
echo "- convex/users/preferences.ts (getUserEmailPreferences query, updateEmailPreferences mutation, shouldSendEmail helper)"
echo ""
echo "Files to modify:"
echo "- convex/schema.ts (add users.emailPreferences field)"
echo "- convex/emailActions.ts (add preference checks to 7 email functions)"
echo ""
echo "Schema addition:"
echo "emailPreferences: v.optional(v.object({"
echo "  groupInvites: v.boolean(),"
echo "  joinRequests: v.boolean(),"
echo "  memberUpdates: v.boolean(),"
echo "  adminTransfer: v.boolean(),"
echo "  newsletters: v.boolean(),"
echo "  reminders: v.boolean(),"
echo "  issueReady: v.boolean()"
echo "}))"
echo ""
echo "Acceptance criteria:"
echo "- users.emailPreferences field in schema (7 boolean fields)"
echo "- Default preferences: all true (opt-out model)"
echo "- getUserEmailPreferences query returns preferences (defaults if not set)"
echo "- updateEmailPreferences mutation saves preferences"
echo "- shouldSendEmail helper checks preferences"
echo "- All 7 email actions check preferences before sending"
echo "- Unit tests passing (6/6)"
echo ""
echo "See Linear issue for full implementation details."
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story EP1 session..."
echo ""

echo "🔷 Story EP2: Frontend Preferences UI (2 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-42"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-EP2: Email Preferences UI Section from Linear issue 2S6-42."
echo ""
echo "Add Email Preferences section to settings page with 7 toggle switches."
echo "Use frontend-dev agent."
echo ""
echo "Files to modify:"
echo "- app/settings/page.tsx (add Email Preferences section BEFORE Group Info section)"
echo ""
echo "UI Requirements:"
echo "- 7 DaisyUI toggle switches (one for each preference type)"
echo "- Labels with descriptions:"
echo "  1. groupInvites: 'Group Invitations' - 'Receive emails when invited to groups'"
echo "  2. joinRequests: 'Join Requests' - 'Receive emails when someone requests to join (admins only)'"
echo "  3. memberUpdates: 'Member Updates' - 'Receive emails when members are added/removed/blocked'"
echo "  4. adminTransfer: 'Admin Transfers' - 'Receive emails when you become a group admin'"
echo "  5. newsletters: 'Monthly Newsletters' - 'Receive monthly newsletter emails'"
echo "  6. reminders: 'Contribution Reminders' - 'Receive reminder emails to submit contributions'"
echo "  7. issueReady: 'Newsletter Ready' - 'Receive emails when new newsletter is published'"
echo ""
echo "Acceptance criteria:"
echo "- Email Preferences section in General tab (before Group Info)"
echo "- 7 DaisyUI toggle switches"
echo "- Fetches preferences on page load"
echo "- Saves when toggled (optimistic update)"
echo "- Success/error toast notifications"
echo "- Loading state (disable toggles while saving)"
echo "- Mobile-responsive (toggles stack vertically)"
echo "- Visual tests at 3 breakpoints"
echo ""
echo "See Linear issue for full implementation details."
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "✅ All sessions launched!"
echo ""
echo "⏱️  Estimated completion time:"
echo "   - Both stories in parallel: 2 hours"
echo ""
echo "📊 Progress tracking:"
echo "   Update: .claude/projects/active/2025-10-email-preferences/STORY_TRACKER.md"
echo ""
