#!/bin/bash

# Newsletter Automation (MVP) - Parallel Session Launcher
# Run this script to launch all stories in separate terminal tabs
# Estimated time: 8 hours total (6 hours wall time with parallel execution)

PROJECT_DIR="/Users/kalyanchandana/Documents/GitHub/2Sat-lite"

echo "🚀 Launching Newsletter Automation (MVP) Sessions..."
echo ""
echo "PROJECT: Newsletter Automation (MVP)"
echo "Linear: https://linear.app/2s6y/project/newsletter-automation-mvp-fc0a5c6fe353"
echo "Stories: 3 (2 parallelizable + 1 integration)"
echo ""

# Phase 1: Parallel Stories (6 hours wall time)
echo "📍 PHASE 1: Parallel Development (run simultaneously)"
echo ""

echo "🔷 Story B1: Cron Job Setup (3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-48"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-B1: Cron Job Setup from Linear issue 2S6-48."
echo ""
echo "Create Convex cron job that triggers newsletter generation every 2nd Saturday at 9 AM UTC."
echo "Use backend-dev agent."
echo ""
echo "Files to create:"
echo "- convex/cron.ts"
echo "- convex/newsletters/orchestrator.ts"
echo "- convex/newsletters/orchestrator.test.ts"
echo ""
echo "Acceptance criteria:"
echo "- Cron job defined with schedule: 2nd Saturday at 9:00 AM UTC"
echo "- Triggers internal.newsletters.orchestrator.runNewsletterGeneration"
echo "- Cron visible in Convex dashboard"
echo "- Manual test passes"
echo "- Unit tests passing (6/6)"
echo ""
echo "See full details: .claude/projects/active/2025-10-newsletter-automation/STORY-B1-cron-job.md"
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story B1 session..."
echo ""

echo "🔷 Story B2: Real Email Sending (3 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-49"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-B2: Real Email Sending from Linear issue 2S6-49."
echo ""
echo "Replace stub email sending in convex/newsletters/sendEmail.ts with real Resend API batch delivery."
echo "Use backend-dev agent."
echo ""
echo "Files to modify:"
echo "- convex/newsletters/sendEmail.ts (replace stub, add batch helper)"
echo "- convex/newsletters/orchestrator.ts (add email sending step)"
echo ""
echo "Files to create:"
echo "- convex/newsletters/sendEmail.test.ts"
echo ""
echo "Acceptance criteria:"
echo "- Stub code removed"
echo "- Real Resend API integration"
echo "- Batch sending (max 100 recipients per call)"
echo "- Newsletter.sentAt updated"
echo "- Newsletter.resendId stored"
echo "- Unit tests passing (12/12)"
echo ""
echo "See full details: .claude/projects/active/2025-10-newsletter-automation/STORY-B2-email-sending.md"
echo "─────────────────────────────────────────────────────────────"
echo ""
read -p "Press Enter after starting Story B2 session..."
echo ""

# Phase 2: Integration Testing (after B1 + B2 complete)
echo "📍 PHASE 2: Integration Testing (WAIT for B1 + B2 to complete)"
echo ""

echo "⚠️  WAIT: Ensure STORY-B1 and STORY-B2 are 100% complete before starting this"
echo ""
read -p "Press Enter when B1 + B2 are COMPLETE to launch Story I1..."
echo ""

echo "🔷 Story I1: E2E Testing (2 hours)"
echo "Linear Issue: https://linear.app/2s6y/issue/2S6-50"
echo ""
echo "Open NEW terminal tab and run:"
echo "─────────────────────────────────────────────────────────────"
echo "cd $PROJECT_DIR"
echo "claude-code"
echo ""
echo "# When Claude asks, paste:"
echo "Implement STORY-I1: E2E Newsletter Automation Testing from Linear issue 2S6-50."
echo ""
echo "Verify complete newsletter automation workflow: cron → generation → email delivery."
echo "Use orchestrator agent."
echo ""
echo "Files to create:"
echo "- tests/e2e/newsletter-automation.spec.ts"
echo "- tests/helpers/newsletter-test-helpers.ts"
echo ""
echo "Acceptance criteria:"
echo "- E2E test suite created (5 tests)"
echo "- All tests passing (5/5)"
echo "- Manual cron verification"
echo "- Real emails delivered (check Resend)"
echo "- Exclusion logic verified"
echo ""
echo "See full details: .claude/projects/active/2025-10-newsletter-automation/STORY-I1-e2e-testing.md"
echo "─────────────────────────────────────────────────────────────"
echo ""

echo "✅ All sessions launched!"
echo ""
echo "⏱️  Estimated completion time:"
echo "   - Phase 1 (B1 + B2 parallel): 3 hours"
echo "   - Phase 2 (I1 sequential): 2 hours"
echo "   - Total wall time: ~5 hours"
echo ""
echo "📊 Progress tracking:"
echo "   Update: .claude/projects/active/2025-10-newsletter-automation/STORY_TRACKER.md"
echo ""
